### ISSUE TITLE
Disable account sign-up

### ISSUE THREAD

**Issue by PiotrKrzyzek** [mauriceoegerli/viewtube-vue#1093]
Currently, anyone and everyone can sign-up to our own instance. It would be awesome to have a setting control either in the interface or via the environment to disable sign-up so no one else can create an account.

**Comment by moisout** [comment]
Awesome idea!

**Comment by Akirainblack** [comment]
Any update on this?

**Comment by adrialcaide** [comment]
any update?

**Comment by simono41** [comment]
any update?

**Comment by moisout** [comment]
I am finishing the authentication rework, afterwards i can implement this

**Comment by moisout** [comment]
You can now disable registration and require login everywhere, implemented in update [0.15.0](https://github.com/ViewTube/viewtube/releases/tag/v0.15.0). Read more here: https://viewtube.wiki/configuration/admin.
