### ISSUE TITLE
Disable access to any part of the interface except when logged in

### ISSUE THREAD

**Issue by PiotrKrzyzek** [mauriceoegerli/viewtube-vue#1094]
When someone goes to your own instance of ViewTube, they are able to browse around and use your system and thus using up your resources (cpu, storage, bandwidth).

It would be wonderful to force login into the system before any browsing or usage can be done. Meaning: no login in? No touchie. Logged in: business as usual.

The idea here is if the ViewTube domain is exposed to the intertubes, no one will be able to do anything on your own instance except those you've explicitly allowed in.

**Comment by moisout** [comment]
You can now disable registration and require login everywhere, implemented in update [0.15.0](https://github.com/ViewTube/viewtube/releases/tag/v0.15.0). Read more here: https://viewtube.wiki/configuration/admin.
