### ISSUE TITLE
Support for short URLs

### ISSUE THREAD

**Issue by rollingmoai** [mauriceoegerli/viewtube-vue#1097]
For example in Invidious and Piped:
https://piped.kavin.rocks/dQw4w9WgXcQ -> https://piped.kavin.rocks/watch?v=dQw4w9WgXcQ

This should be implemented as short URLs from youtube do not redirect properly from [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect).

**Comment by moisout** [comment]
@rollingmoai Good news, this is now implemented :D. It only took more than 2.5 years 😅.
