### ISSUE TITLE
Error Loading Homepage

### ISSUE THREAD

**Issue by cinetube** [mauriceoegerli/viewtube-vue#1108]
Here is my Docker Compose - 

<pre>
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:latest
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_API_URL=https://api.viewtube.io/
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_JWT_SECRET=secret
      - VIEWTUBE_JWT_EXPIRATION_TIME=43200
      - VIEWTUBE_CURRENT_DOMAIN=viewtube.io
      - VIEWTUBE_DATA_DIRECTORY=/data
      - VIEWTUBE_PUBLIC_VAPID=BNeP75BAjVb3s3scWk_kjBBwd3nXwMDLvbG5m0vP9h52NwNT5orzE-844VdLlkZJ4ywcvAAXhIFpkW-DDRr-L9E
      - VIEWTUBE_PRIVATE_VAPID=T7h9XAYalg-oMQnIL9V8CISSNpqY7x4F8otAuIZgXcI
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

networks:
  viewtube:
</pre>

Result - 
<img width="911" alt="Screenshot 2021-11-16 223545" src="https://user-images.githubusercontent.com/23441775/142027035-8e3c41fd-8939-4e45-8868-a025e3efe235.png">

How can I solve this issue?

**Comment by moisout** [comment]
Hi, have you adjusted the domain and api url values ti match your setup exactly?
The api url should be your-domain.com/api/.
If its an IP it should be for example 83.473.4.2:8066/api/.
