### ISSUE TITLE
Login doesn't do anything

### ISSUE THREAD

**Issue by 12nick12** [mauriceoegerli/viewtube-vue#1114]
### Describe the Bug

I create an account and it's there since I can't sign up again with the same username.

### Steps to Reproduce the Bug
When I go to log in it says I'm logged in, but nothing happens.

### Device Info 

- Device: X1 Yoga Gen3
- OS: Windows 10
- Browser: Firefox/Chrom

**Comment by moisout** [comment]
Hi, i can't reproduce this. Can you maybe send me a private email (viewtube@m-o.dev) with your username, so i can check it out?

**Comment by 12nick12** [comment]
This is on my own instance, not your dev instance.

**Comment by moisout** [comment]
Ah, i see. Are you connecting to it using an ip or a domain?

**Comment by brasilikum** [comment]
Seem to have the same issue.
I am hosting it on a domain. API URL is set

I checked the network:
- Login returns 204
- Next requests (eg. Profile) return 401

**Comment by brasilikum** [comment]
I think I know why:

```
Authentication=xxx; HttpOnly=true; Path=/; Secure=true; Domain=localhost; Max-Age=43200
```

Cookie domain is not set correctly. This should probably default to URL, no?

**Comment by moisout** [comment]
Ah, this should be fixed in v0.9. 
Please beware the environment variables have changed. They are documented in the installation wiki, you can remove the unmentioned ones from your setup.

https://github.com/ViewTube/viewtube-vue/wiki/Installation#environment-variables

**Comment by brasilikum** [comment]
I just tested with 0.9. It's still broken

**Comment by moisout** [comment]
Could you maybe post your docker-compose/docker run, so i could reproduce it?

**Comment by 12nick12** [comment]
I just used the example docker-compose from https://github.com/ViewTube/viewtube-vue/wiki/Installation#environment-variables and it is working. Thank you.
