### ISSUE TITLE
Raspberry PI: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Christoph-87** [mauriceoegerli/viewtube-vue#1122]
### Describe the Bug
The docker image does not run on my Raspberry Pi. In the logs the container shows standard_init_linux.go:228: exec user process caused: exec format error

uname -a shows
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

### Steps to Reproduce the Bug
1. Docker Compose file is:
  viewtube:
        container_name: viewtube
        restart: unless-stopped
        image: mauriceo/viewtube:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /share/Docker/viewtube/data:/data
        environment:
            - VIEWTUBE_API_URL=https://api.viewtube.io/
        ports:
            - 8066:8066

2. run docker-compose up -d viewtube
3. docker logs viewtube shows: standard_init_linux.go:228: exec user process caused: exec format error

### Expected Behaviour
It should run and I should be able to access the application on port 8066.

### Screenshot/Screen recording
n/a

### Device Info 
- Device: Raspberry Pi
- OS: Linux
- Browser: n/a
- Version: n/a
- 
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

### Additional Context
I think that maybe the armv7l architecture is not supported yet?

**Comment by moisout** [comment]
Hi, i'm working on raspi support, please see #979
