### ISSUE TITLE
Username should be case insensitive

### ISSUE THREAD

**Issue by brasilikum** [mauriceoegerli/viewtube-vue#1133]
### Describe the Bug

Usernames are case sensitive. This can cause confusion for users.

### Steps to Reproduce the Bug

1. Sign up with any username. Make any char uppercase (this easily happens with mobile autocomplete)
2. Sign in with the same username but with the char lowercase.
3. It does not recoginize the user

### Expected Behaviour

3. Usernames should be case-insensitive. That means any case should be accepted, but converted to lowercase before creating / finding in the db

### Device Info 

- Device: M1 Mac Mini
- OS: MacOS
- Browser: Brave
- Version: 0.9

**Comment by sdfg2** [comment]
Case sensitivity increase security (marginally) by increasing the the attack surface - there are far more combinations of upper and lower case characters.  Harder for brute-force.  But anything that is case sensitive should be mentioned as being that way.
