### ISSUE TITLE
Some videos not playing

### ISSUE THREAD

**Issue by TheCrimsonLady** [mauriceoegerli/viewtube-vue#1230]
### Describe the Bug

Some Videos will not play at all (loading animation), some have a moving video status bar but no sound or moving picture.

### Steps to Reproduce the Bug

Choose random video and sometimes it will not play. Examples:
https://www.youtube.com/watch?v=6ApOiMpGz60
https://www.youtube.com/watch?v=nfDoml-Db64

### Expected Behaviour
Video should start to play instead of loading forever or showing other weird behaviour 

### Device Info 

- Device: iPhone 12, iMac 27"
- OS: iOS 15.3, macOS 12.2
- Browser: Safari & Firefox --> same behaviour in both browsers
- Version: ViewTube version: image: mauriceo/viewtube:0.9, Safari version 15.3 (17612.4.9.1.5), Firefox version 96.0.3

###Comments

I already tried redeploying the containers (deployed via docker-compose) while retaining the volumes/databases, I also added in another attempt my YouTube cookie and my YouTube name with and without quotation marks in the docker-compose.yaml. But this did not change the behaviour.

Also, if related: the popular videos section of the landing page does not work.
I'd be grateful for any help.

**Comment by ForceConstant** [comment]
I have just installed viewtube using docker, and am getting similar results. Some videos work, and some just keep loading forever.

**Comment by followsound** [comment]
I too have the same behavior (not loading, not playing videos, no popular) with viewtube running in containerd on Kubernetes (can reproduce with viewtube running in docker locally too).

I can play videos on the same machine in Chrome `103.0.5060.134`, so I'm thinking it isn't anything to do with my Kubernetes/nginx/etc setup.

Viewtube: `v0.9`
Safari: `Version 15.5 (17613.2.7.1.8)`
macOS: `12.4 (21F79)`

**Comment by moisout** [comment]
Revisiting this, the videos seem to work now :) If there are any more problems, feel free to open an issue

**Comment by followsound** [comment]
Can confirm I am not seeing the issue anymore

**Comment by haitispaceagency** [comment]
This seems to still be affecting me. I've only set it up today.

**Comment by Wurzelmann** [comment]
Same here. Installed with Docker, set up nginx and only seeing buffering messages in nginx for some videos.
