### ISSUE TITLE
error loading comments every video

### ISSUE THREAD

**Issue by ghost** [mauriceoegerli/viewtube-vue#1241]
### Describe the Bug
error loading comments appears under each videos

### Steps to Reproduce the Bug

11. Go to 'any video'
3. Scroll down to 'where the comments should be'
4. See the error

### Expected Behaviour
comments

### Device Info 

- Browser: [e.g. Firefox, Safari]
- Version: [e.g. 22]

**Comment by moisout** [comment]
This occurred because of an old version of yt-comments-scraper, and is fixed now.

**Comment by SudharakaP** [comment]
@mauriceoegerli : This still seems to be occurring. 

![image](https://user-images.githubusercontent.com/12435965/223566129-15681bfd-7323-4200-bd20-fad97bc4a0ef.png)

**Comment by moisout** [comment]
I'm gonna replace the library for the comments soon to fix this issue. I'm currently working on some bugfixes for the video player, i'll work on this afterwards.

**Comment by SudharakaP** [comment]
> I'm gonna replace the library for the comments soon to fix this issue. I'm currently working on some bugfixes for the video player, i'll work on this afterwards.

@mauriceoegerli : Would you be able to open an issue or suggest the changes or library you have in mind? Maybe I can try to fix this in my spare time. 😸

**Comment by moisout** [comment]
> 

I opened one here, gonna add more details soon #1791
