### ISSUE TITLE
Nothing happening after ℹ Primary node started: pid 1

### ISSUE THREAD

**Issue by FunDeckHermit** [mauriceoegerli/viewtube-vue#1248]
### Describe the Bug

Webpage stays blank after running the docker compose file. Redis and Mongo-DB are happily chugging away but the ViewTube service stops after the first line. 

Docker Compose log here: [LINK](https://www.toptal.com/developers/hastebin/awuwayodab.pl)

### Steps to Reproduce the Bug
1. Use the latest Docker
2. Use the latest [Docker Compose](https://github.com/docker/compose/releases)
3. Copied this compose file in a [docker-compose.yml ](https://github.com/ViewTube/viewtube-vue/wiki/Installation#docker-compose-example) file
4. Edited VIEWTUBE_URL to http://192.168.1.205:8066/ (also tried localhost, the IP of the webbrowser client and my domain name)

### Expected Behaviour

ViewTube visible in the browser

I was expecting a log like in [this Issue. ](https://github.com/ViewTube/viewtube-vue/issues/1088)

### Screenshot/Screen recording

![image](https://user-images.githubusercontent.com/5075692/153678196-a0a2d16b-e818-49a5-aa89-f37d7fa95fb9.png)

### Device Info 

- Browser: Firefox
- Version: [e.g. 22]

### Additional Context

Tried a Hello World Docker webserver and that's running great. So no firewall blocking. 
![image](https://user-images.githubusercontent.com/5075692/153678859-85de829a-3d65-4846-aab9-52d92d7fe7e9.png)
Stopping also takes ages (365 seconds) so I assume the application is stuck somewhere.

**Comment by moisout** [comment]
Weird... it really seems to be stuck somewhere. What hardware are you running on exactly?

**Comment by FunDeckHermit** [comment]
Nothing strange. LXC container running on Proxmox. Proxmox running on old i5-8250u hardware.

**Comment by FunDeckHermit** [comment]
Can I increase the log level somehow? I could also check older versions and check where it starts failing.

This is my first time running it, so no past history of it working.

**Comment by moisout** [comment]
You could try to disable clustering by setting VIEWTUBE_CLUSTERED=false

**Comment by FunDeckHermit** [comment]
Yeah that seemed to fix the issue. 
If you want to replicate it: 
- Proxmox 7.1
- Latest Docker version
- Docker Compose V2.2.3
