### ISSUE TITLE
Single user mode

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1303]
### description
Have a single user mode - no need to log in, but everything is still saved in the database.

### acceptance criterias
- [ ] Have single user mode.

**Comment by moisout** [comment]
You can now disable registration and require login everywhere, implemented in update [0.15.0](https://github.com/ViewTube/viewtube/releases/tag/v0.15.0). Read more here: https://viewtube.wiki/configuration/admin.

Disabling login entirely is not possible, but you could create an account only for yourself and then use that.
