### ISSUE TITLE
Option to replace homepage with subscriptions

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1306]
### description
At the moment it's possible to add subscriptions to the top of the home page.  It would be nice to have the option to replace the homepage with subscriptions page entirely, not showing popular videos at all.  Maybe make the homepage customizable with different widgets?  Specific channels, popular, subscriptions etc.

### acceptance criterias
- [ ] Option to replace homepage with subscriptions
- [ ] Bonus points to make homepage customizable with widgets

**Comment by moisout** [comment]
You can now enable/disable popular videos and subscriptions on homepage individually, making this possible.
