### ISSUE TITLE
Channel bar obscures video information for bottom row of videos

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1308]
### Describe the Bug

Channel bar obscures video information for bottom row of videos

### Steps to Reproduce the Bug

1. Go to a channel
2. Scroll to the bottom
3. Can't see video information

### Expected Behaviour

See all video information

### Screenshot/Screen recording

![image](https://user-images.githubusercontent.com/5736478/158632589-7ca71e80-b2d6-4c90-a1dd-8232da304cfd.png)

### Device Info 

- Device: Desktop, Mobile, Tablet
- OS: Arch, Android
- Browser: vivaldi, chromium, firefox, vivaldi-mobile, fennec

### Additional Context

Solution: add `margin-bottom: 60px;` to `.channel .video-sections-container`:
![image](https://user-images.githubusercontent.com/5736478/158632445-e9106e87-dd58-4fa3-994a-87a391e75287.png)

**Comment by moisout** [comment]
The channel page has since been rewritten, it doesn't have this issue anymore
