### ISSUE TITLE
Not all player controls work on Android

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1309]
### Describe the Bug

When playing a video on mobile, the play/pause, settings, and fullscreen buttons don't work.

### Steps to Reproduce the Bug

1. Open viewtube video on mobile
2. Press play/pause, settings, or fullscreen
3. Nothing happens

### Expected Behaviour

The buttons work

### Device Info 

- Device: Mobile, Tablet
- OS: Android
- Browser: vivaldi-mobile, fennec

### Additional Context

Might be more general than just Android, but I don't have anything else to test with.

**Comment by moisout** [comment]
Video player improvements are available on dev.viewtube.io
