### ISSUE TITLE
Can’t press settings icon

### ISSUE THREAD

**Issue by Mennaruuk** [mauriceoegerli/viewtube-vue#1310]
### Describe the Bug

Hey Maurice, hope you’re doing okay 👋

I’ve been facing this issue where I cannot press the gear icon in the video player. This is occurring on iOS Safari.

### Steps to Reproduce the Bug

Upon tapping, the settings should appear.

### Screenshot/Screen recording

(Apple doesn’t allow taps to be shown, but yes, I’m pressing on the gears icon towards the video’s end.)

https://user-images.githubusercontent.com/52135169/158872340-ed4378e8-986a-484b-bae9-a78758587f6a.MOV

### Device Info 

- Device: iPhone X
- OS: 15.3
- Browser: Safari
- Version: 15.3

### Additional Context
Thank you very much for your help!

**Comment by sdfg2** [comment]
Do the other controls work?  I have a similar situation on Android.

**Comment by Mennaruuk** [comment]
Actually right. None of the controls work.

**Comment by apblair** [comment]
Same issue with Firefox on Android. None of the controls below the line (gear, fullscreen, etc) can be clicked. FF 102.2.1 Android 5.1

**Comment by moisout** [comment]
This has been fixed, check https://dev.viewtube.io
