### ISSUE TITLE
Integrate Return YouTube Dislike

### ISSUE THREAD

**Issue by aparatext** [mauriceoegerli/viewtube-vue#1323]
## Description
Return YouTube Dislike is an extension and an API that estimates the number of dislikes a video has. Clients can send all dislikes to them to make an estimate more accurate.

## Acceptance criteria
- [x] Re-add the rating UI
- [x] Request dislikes from RYD API
- [ ] Opt. Send dislikes to RYD API.

## Resources
 - [API docs](https://www.returnyoutubedislike.com/docs)

**Comment by davidcollini** [comment]
RYD has multiple issues, see TeamNewPipe/Newpipe#7469

**Comment by moisout** [comment]
Since ViewTube proxies any request, privacy would not be a concern like with NewPipe. This would be a great feature!
But I think I won't add the voting functionality because you could only dislike, which would be weird.

**Comment by moisout** [comment]
Added in #1373!
