### ISSUE TITLE
connection speed

### ISSUE THREAD

**Issue by senolfndk** [mauriceoegerli/viewtube-vue#1413]
videos load very slowly or not at all
![Ekran görüntüsü 2022-05-08 201005](https://user-images.githubusercontent.com/52818836/167307464-a3351467-c8de-4195-9d7d-27cc26c35ce7.png)

**Comment by moisout** [comment]
My server can sometimes get overloaded if many people are using the service at the same time. There is not much I can do, except improve the efficiency of the app, which is always a priority. If you want to, you can host your own instance for yourself so you can enjoy faster speeds. https://viewtube.wiki/installation
