### ISSUE TITLE
Local subscriptions

### ISSUE THREAD

**Issue by PowerMan2206** [mauriceoegerli/viewtube-vue#1506]
Would it be possible to have subscriptions saved locally to something like cookies? Making an account for something that's supposed to be a privacy-friendly alternative feels kinda weird. Not in a `I don't trust you` kind of way, but in a `I prefer it like this` kind of way, y'know?

**Comment by sdfg2** [comment]
Sure!

[Install it locally.](https://github.com/ViewTube/viewtube-vue/wiki/Installation)  This is a self hosted app. :-)

**Comment by PowerMan2206** [comment]
Ah, so I'd be creating an account with myself, I see. I'll look into it, thanks
