### ISSUE TITLE
Import viewtube exported subscriptions

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1516]
I'm not sure if I'm just being blind, but is it really not possible to import a subscription list that has been exported from another viewtube instance?

**Comment by moisout** [comment]
This is not yet possible, but i'll keep it on my list.

**Comment by nargacu83** [comment]
@moisout Should this issue be closed? It looks like it's implemented. I just did this a couple of days ago.

**Comment by moisout** [comment]
> @moisout Should this issue be closed? It looks like it's implemented. I just did this a couple of days ago.

Yes, thanks, i forgot about this
