### ISSUE TITLE
MPEG-DASH Enabled. Videos don't play

### ISSUE THREAD

**Issue by psybernoid** [mauriceoegerli/viewtube-vue#1517]
Enable MPEG-DASH in user settings, click on a video. I used the LTT Apple Finally did it.... video from the recommendations on the front page (BB8OvBBzl_s) video seems to be constantly biffering.

Disabling MPEG-DASH and launching the same video works.

I've tested this on my own, self-hosted instance and with viewtube.io
![Screenshot 2022-10-04 153306](https://user-images.githubusercontent.com/600235/193847495-acb3281d-544d-4fa0-bec8-5fc83a37cb5c.png)

**Comment by moisout** [comment]
The current MPEG DASH is not very reliable. I will have to look into it.

**Comment by moisout** [comment]
The MPEG-DASH implementation has been updated, it works more reliably now
