### ISSUE TITLE
Custom Sponsorblock settings

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1520]
### description
The official sponsorblock has been having significant problems recently.  It would be nice if we could point viewtube at our own hosted sponsorblock server.

**Comment by moisout** [comment]
I didn't know there were self hosted instances, thanks for letting me know

**Comment by patgruber** [comment]
Implemented in #2799

**Comment by moisout** [comment]
Will be released soon
