### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by Ulysses-101** [mauriceoegerli/viewtube-vue#1522]
When clicking on a video I get Invalid or unexpected token?

{
  "requestConfig": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 30000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {
      "FormData": null
    },
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "baseURL": "http://x.x.x.x:8066/api/",
    "withCredentials": true,
    "method": "get",
    "url": "videos/BAo5C2qbLq8"
  },
  "responseData": {
    "status": 500,
    "message": "Invalid or unexpected token"
  },
  "message": "Request failed with status code 500"
}

(http://x.x.x.x:8066/watch?v=BAo5C2qbLq8#)

Server:
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
Device="Jetson NANO"

Client:
MacBook Air
OS = Ventura
Browser: FF

Any help would be much appreciated.

Viewtube docker logs:
ℹ Primary node started: pid 1
ℹ Worker node started: pid 20
ℹ Worker node started: pid 26
start Starting in clustered mode
ℹ Worker node started: pid 13
ℹ Worker node started: pid 14
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
(node:26) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
(node:20) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
(node:14) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
(node:13) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
ready Server listening on http://0.0.0.0:8066
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".

**Comment by Ulysses-101** [comment]
Weirdly the vidoes have started working again, don't know why as I didn't change anything.

**Comment by moisout** [comment]
Sometimes youtube changes stuff arbitrarily, so this can happen

**Comment by moisout** [comment]
The new update should make things more robust, so I'll close this for now. If there are any problems, feel free to open an issue.
