### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Metastem** [mauriceoegerli/viewtube-vue#1526]
I don't understand how to run it on docker, can someone give me more detailed about how to deploy it on docker

**Comment by Svenito** [comment]
Are you familiar with Docker already?

The easiest way is to use docker-compose. The wiki has an example docker-compose file that works, along with setup instructions
https://github.com/ViewTube/viewtube-vue/wiki/Installation

**Comment by moisout** [comment]
I will update the documentation to be more complete and beginner friendly in the future. If you think there is something missing or incorrect, please open a specific issue.
