### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by wnhrt** [mauriceoegerli/viewtube-vue#1530]
### description
Adding support for SQLite would simplify the setup process and management of lightweight instances.
This feature would especally improve the experience with [single user mode](https://github.com/ViewTube/viewtube-vue/issues/1303) implemented.

### acceptance criterias
- [ ] Add support for SQLite

**Comment by moisout** [comment]
This would be quite a big undertaking, because db stuff is all based on mongodb. I will focus on stability and bugs first, hope you understand :)

**Comment by jerrywoo96** [comment]
> This would be quite a big undertaking, because db stuff is all based on mongodb. I will focus on stability and bugs first, hope you understand :)

if that is the case, then would running mongodb within the container itself be a plausible solution? With minimal configuration, the user could choose to use the built-in mongodb instance which would simplify the setup process instead of providing an address to an externally hosted mongodb server.

**Comment by moisout** [comment]
Yeah that would be an option! I'll look into it

**Comment by mvanduijker** [comment]
@jerrywoo96 I made an all in one container which you can try: https://github.com/mvanduijker/viewtube-all-in-one

**Comment by moisout** [comment]
@mvanduijker Wow very awesome!

**Comment by moisout** [comment]
Moving away from mongodb is not intended.

The all-in-one image is linked in the wiki, https://viewtube.wiki/installation/docker#all-in-one-setup-by-mvanduijker.
