### ISSUE TITLE
video quality dose not change 

### ISSUE THREAD

**Issue by syfullah23** [mauriceoegerli/viewtube-vue#1668]
Dear Developer,

Video quality dose does not adjust to higher quality even when we select the desired quality video source link appears to be the same. 

In my case video was playing 640x360 - 412.0 kB/s then i did select 1280x720 - 1.2 MB/s  but the video seems the same playing 640X360 frame. 

![image](https://user-images.githubusercontent.com/123854643/216296451-fb319594-241b-40ef-9fad-4a085661659e.png)

Thanks

**Comment by gpijat** [comment]
I have the same issue, any fix coming soon ? Thank you !

**Comment by moisout** [comment]
If you disable "automatically adjust", you can choose the quality yourself. If auto adjust is enabled it might not be very accurate.
