### ISSUE TITLE
Don't display correct typo when no results

### ISSUE THREAD

**Issue by maboroshin** [mauriceoegerli/viewtube-vue#1804]
### Describe the Bug

Unexpected search results were displayed.

~~Only numbers, alphabets, and other ASCII characters can be used for searches. It does not support searches using Kanji characters.~~ (misunderstanding)

### Steps to Reproduce the Bug

1. Search for Japanese rapper "舐達磨" : https://viewtube.io/results?search=%E8%88%90%E9%81%94%E7%A3%A8
2. Arabic characters without Kanji characters in the results. His name is maybe "Null".

### Expected Behaviour

Three Asian rappers with tattoos appear in the results.
https://piped.video/results?search_query=%E8%88%90%E9%81%94%E7%A3%A8

### Device Info

- Device: PC
- OS: WIN10
- Browser: Chrome
- Version: 111

**Comment by moisout** [comment]
This is an interesting one! Thanks for reporting, I'll take a look

**Comment by maboroshin** [comment]
@mauriceoegerli
Sorry. The third letter was a typo.
The correct kanji is 舐達**麻** .

ViewTube seems to display a creator named "null" when there is no result.

Other engines seem to show candidates with a "Did you mean" feature that suggests typos.

**Comment by moisout** [comment]
The library for search results has since been replaced, unfortunately removing support for "did you mean..." prompts :(
All kinds of characters are however supported :)
