### ISSUE TITLE
Connection refused using docker-compose

### ISSUE THREAD

**Issue by manuelkamp** [mauriceoegerli/viewtube-vue#1864]
I use a fresh LXC with Ubuntu 20.04 on my Proxmox cluster. Docker-CE and Docker-Compose installed. I used the following docker-compose.yml:

`version: '3'
services:
  viewtube:
    restart: unless-stopped
    # Or use mauriceo/viewtube:dev for the development version
    image: mauriceo/viewtube:latest
    # ViewTube will not start until the database and redis are ready
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    # Make sure all services are in the same network
    networks:
      - viewtube
    volumes:
      # This will map ViewTube's data directory to the local folder ./data/viewtube/
      - ./data/viewtube:/data
    environment:
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
    ports:
      - 8066:8066
  viewtube-mongodb:
    restart: unless-stopped
    image: mongo:5
    networks:
      - viewtube
    volumes:
      - ./data/db:/data/db
  viewtube-redis:
    restart: unless-stopped
    image: redis:7
    networks:
      - viewtube
    volumes:
      - ./data/redis:/data
networks:
  viewtube:
`

The container is starting, but I can not access the site from any browser in my network. using http://srv-viewtube.domain.local:8066 - Browser says "ERR_CONNECTION_REFUSED"

In addition to that, also on the server it seems to be not working:
`root@srv-viewtube:~/viewtube# wget localhost:8066
--2023-03-29 18:47:08--  http://localhost:8066/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8066... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8066... failed: Connection refused.
`

What am I missing or doing wrong?

**Comment by moisout** [comment]
Maybe there is a mistake in the default docker compose on the wiki. I will test it and get back to you.

**Comment by thimplicity** [comment]
Same issue here, did you identify the problem/resolution?

**Comment by manuelkamp** [comment]
No, I tried another "competitor", where the docker container worked fine. Just recently it stopped working out of nowhere, but restoring a previous backup solved it. But thats another topic.

**Comment by thimplicity** [comment]
Would you share which competitor?

**Comment by manuelkamp** [comment]
Piped

**Comment by moisout** [comment]
Piped and ViewTube are not competitors :). In the end, you, the user, get to decide which one works best for you.

**Comment by thimplicity** [comment]
Very true, unfortunately I cannot get Viewtube to work in my selfhost environment, because the frontend cannot get a connection to the mongo db.

**Comment by moisout** [comment]
I would recommend you try to run it again if you'd like to, there have been many improvements in the recent releases
