### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Lippiece** [mauriceoegerli/viewtube-vue#1880]
### Steps to Reproduce the Bug

1. Go to https://viewtube.io

### Expected Behaviour

See the site.

### Screenshot/Screen recording

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/47634624/230074329-c66478bb-71fc-4e84-8744-aaa8a222b665.png)

</details>

### Device Info

- Device: PC
- OS: OpenSUSE Tumbleweed
- Browser: Vivaldi
- Version: 5.8.2978.3 (Official Build) snapshot (64-bit) 

<details>
<summary>Error</summary>

```
I got an error when visiting viewtube.io/.

Error code: 1020
Ray ID: 7b31a507688c0a4b
Country: RU
Data center: ams13
IP: 37.146.232.110
Timestamp: 2023-04-05 12:02:52 UTC
```

</details>

Please don't tell me you just ban Russian IPs.

**Comment by moisout** [comment]
I am sorry, unfortunately I had to block Russian IPs because I have been spammed with DMCA takedown requests and lawyer letters from Russia. If you can, use a VPN or host your own instance. https://viewtube.wiki/installation

**Comment by Lippiece** [comment]
I understand, thank you for clarifying.

**Comment by moisout** [comment]
@Lippiece The company who was sending the requests and letters has exited Russia, I have reopened access.

**Comment by WeAreLiving1984** [comment]
> @Lippiece The company who was sending the requests and letters has exited Russia, I have reopened access.

I'm timing out with russian IP. And getting "Sorry, you have been blocked" with [byedpi](https://github.com/hufrea/byedpi).
