### ISSUE TITLE
Internal error when playing video

### ISSUE THREAD

**Issue by SudharakaP** [mauriceoegerli/viewtube-vue#1890]
### Describe the Bug

Starting a few days it seems that trying to play any video gives a server error (see screen-cast below). 

[no-video.webm](https://user-images.githubusercontent.com/12435965/230731521-26fb1f09-43a9-48e2-9fa0-8749294925fc.webm)

### Steps to Reproduce the Bug

1. Go to https://viewtube.io/
2. Click on any video
3. See the error

### Device Info

- Device: Computer
- OS: Pop!_OS 22.04 LTS
- Browser: FireFox
- Version: 111.0.1 (64-bit)

**Comment by moisout** [comment]
Hi, I am currently working on a fix

**Comment by JamsRepos** [comment]
Thanks for looking into this, newcomer to this project! Absolutely love the layout and features, can't wait to start using once fixed.

**Comment by MisterDeee** [comment]
I'm also getting this error:

Error loading video

N.data is undefined

One thing to note, it's only on Firefox. I can play the videos fine on Chrome. I get a different error on Edge:

Error loading video
Cannot read properties of undefined (reading 'prog

Nothing in the Docker logs for either of those errors.

**Comment by JamsRepos** [comment]
There's also internal errors when trying to import subscribers and the subscribe button doesn't work. I would assume it's all related.

**Comment by JamsRepos** [comment]
What's the status on this?

**Comment by Savanta** [comment]
Any news?

**Comment by moisout** [comment]
Fix is underway!

**Comment by moisout** [comment]
Stuff works again on dev.viewtube.io. It's still quite slow however, i am looking into it.

**Comment by Savanta** [comment]
Still 403 forbidden in console on firefox, windows. Same on linux

**Comment by moisout** [comment]
I have released version 0.11.0. MPEG-DASH is now enabled by default, videos should be a whole lot smoother and more reliable!
