### ISSUE TITLE
Error when loading video

### ISSUE THREAD

**Issue by Ean117** [mauriceoegerli/viewtube-vue#1893]
### Describe the Bug

When going on any video (I have tested on many videos, so its safe to say that this is widespread), it gives me an error loading the video. Specifically an error code 500

### Steps to Reproduce the Bug

1. Go to any video
2. Click on the video
3. See the error

1.
2.
3.

### Expected Behaviour

Expected behavior is when clicking on any video, it gives an error notification

### Screenshot/Screen recording

![Screenshot 2023-04-10 8 27 31 PM](https://user-images.githubusercontent.com/124911788/231033045-f712cbaf-5b0e-48c4-b8eb-520df8588dcb.png)

### Device Info

- Device: [Chromebook Lenovo 100e Gen 2 AST]
- OS: [chromeOS Version 111.0.5563.118]
- Browser: [Chrome]
- Version: [111.0.5563.118]

**Comment by moisout** [comment]
I am tracking progress on this issue here #1890
