### ISSUE TITLE
Support arm64 in all builds

### ISSUE THREAD

**Issue by nicotsx** [mauriceoegerli/viewtube-vue#1896]
### description

Hello, we are trying to use viewtube on arm64 but it seems that the tagged version 0.10 on docker hub has only support for amd64 where the nightly build does support 3 different types. Is it something expected?

![Screenshot 2023-04-13 at 23 36 45](https://user-images.githubusercontent.com/47644445/231888379-44b58cbb-e554-45e8-b87b-4a7a64a494ab.png)
![Screenshot 2023-04-13 at 23 37 08](https://user-images.githubusercontent.com/47644445/231888453-af43b526-8b79-4fd7-aa7e-1153622da605.png)

### acceptance criterias

- [ ] Make all versions available as arm64 and arm/v7

**Comment by moisout** [comment]
I have not made a release yet with arm64, but as soon as 0.11 is out there will be arm64 builds of it. I will release that as soon as the video page is fixed.
