### ISSUE TITLE
Configurable subscription interval time

### ISSUE THREAD

**Issue by pmoscode** [mauriceoegerli/viewtube-vue#1928]
### description

Currently the subscription feed will be refreshed every hour. I cannot find any config to change this. So, it is possible to make the refresh interval configurable?

### acceptance criterias

- Set an env variable like "SUBSCRIPTION_FEED_REFRESH_RATE". The value is an integer which represents minutes.
- Use this variable to schedule refresh interval.

**Comment by iwannet** [comment]
Yeah how can we do this ?

**Comment by iwannet** [comment]
Any work on this ? I really would like to be able to set this on my selfhosted server, or maybe a button to refresh the subscriptions on command

**Comment by pmoscode** [comment]
I dropped the usage of ViewTube.
Found another solution.

**Comment by iwannet** [comment]
> I dropped the usage of ViewTube.
> Found another solution.

Whats your solution ? Piped ?

**Comment by moisout** [comment]
This has since been released with version [0.16.0](https://github.com/ViewTube/viewtube/releases/tag/v0.16.0)
