### ISSUE TITLE
Add a list of (active) instances

### ISSUE THREAD

**Issue by sereksim** [mauriceoegerli/viewtube-vue#1941]
### description

It would be great if there was a list of instances. Without that it is impossible to know whether there are more public instances of viewtube besides viewtube.io.

Additionally, for Viewtube to be added to the [browser extension libredirect](https://github.com/libredirect/browser_extension), which automatically redirects many sites to alternative foss-frontends, there has to be a list of instances. It would be great to have viewtube in libredirect, but without a list that is impossible.
(Edit: [link to the corresponding issue at libredirect](https://github.com/libredirect/browser_extension/issues/115))
### acceptance criterias

- [ ] add a list where new public instances of viewtube can be added

**Comment by Mennaruuk** [comment]
This is absolutely necessary! Not only would it encourage use of ViewTube, but it would lessen the pressure on the two (and only) available public instances, both run by the ViewTube team.

**Comment by moisout** [comment]
There is a list on https://viewtube.wiki/about/instances. No one has submitted their instance yet tho :) Maybe i need a more prominent note about it.
Do i need to provide it in another format (e.g. json)?

**Comment by sereksim** [comment]
> Do i need to provide it in another format (e.g. json)?

I don't know the specific requirements, but it needs to be fetchable by their python scipt, see https://libredirect.github.io/faq.html#suggest_frontend, https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from and https://github.com/libredirect/instances

**Comment by moisout** [comment]
The instance list in the wiki seems to be enough. If there is demand for a json list in the future, I'll look into adding one.
