### ISSUE TITLE
Cannot subscribe to any channel and Subscription list import from csv not working either

### ISSUE THREAD

**Issue by mahenkpatel** [mauriceoegerli/viewtube-vue#1950]
### Describe the Bug

Installed viewtube on Armv8 using the nighly  docker image. I cannot subscribe to any channel. Clicking on **subscribe** button change the button to **unsubscribe** giving an impression that its subscribe but if the page is refreshed it returns back to **subscribe** button.

A

Tested on multiple browsers, disabling all addons, same result.

### Steps to Reproduce the Bug

1. Go to any channel or any video
2. Click on **Subscribe** button
3. The button changes to **Unsubscribe** giving impression that the channel is subscribed
4. Refresh the page, the button changes back to **Subscribe**.

### Screen Recording

https://i.imgur.com/n7G3kaA.gif

### Expected Behaviour

Clicking on subscribe button should subscribe to channel

### Device Info

- Device: MacOS, Windows
- OS: Macos ventura, Windows 11
- Browser: Firefox, Safari
- Version: Firefox 113.0.1, Safari 16.4

### Additional Context

Installed using the docker-compose with nightly image on Ubuntu 20.04, ArmV8

**Comment by Viellieb** [comment]
@mahenkpatel Did you manage to get it working? I got the same problem but I suspect some configuration issue.

**Comment by mahenkpatel** [comment]
@Viellieb Couldn't get this working so uninstalled it and am not using it anymore.

**Comment by lostrockets** [comment]
same problem for me

**Comment by ewoks** [comment]
just tested both and can confirm the issue is not present anymore. IMO we can close this @moisout
