### ISSUE TITLE
Cannot load video with saved watch time

### ISSUE THREAD

**Issue by Melonchanism** [mauriceoegerli/viewtube-vue#1961]
### Describe the Bug

When trying to continue watching a video with saved watch time, an error appears and the video doesn't play

### Steps to Reproduce the Bug

1. Create an account and sign in
2. watch a video
3. go back to the main screen
4. try to play the same video again
5. see the error `Cannot read properties of undefined (reading 'progressSeconds')`

### Expected Behaviour

The video should load with the saved watch time

### Screenshot/Screen recording

![image](https://github.com/ViewTube/viewtube/assets/121840186/f32ab720-841b-45f1-adbb-355af0aba087)

### Device Info

- Device: iPhone 14, hp chromebook
- OS: iOS 16.4, ChromeOS 114.0.5735.119 
- Browser: Safari PWA, chrome
- Version: 16, 114.0.5735.119

### Temporary Fix

Not using watch time by turning off history in settings

**Comment by gpijat** [comment]
Hey, I have the same issue happening on Chrome.
Version: `Version 118.0.5993.70 (Official Build) (64-bit)`

**Comment by moisout** [comment]
I am currently working on a new video player #2387. It will fix this issue
