### ISSUE TITLE
Issues with 0.10, dev, latest, and nightly (and viewtube.io)

### ISSUE THREAD

**Issue by JesseWebDotCom** [mauriceoegerli/viewtube-vue#1963]
Great project - just started using it in the past hour.  Here are some issues I discovered:

- subscriptions work in 0.10 and latest but not in dev, and nightly
- popular videos do not work 0.10 and latest but work in dev, and nightly
- if you add subscriptions in 0.10 or latest and then switch to dev, or nightly - they will load but you can't add more

Subscriptions are also broken at https://viewtube.io/subscriptions (which I assume are using dev or nightly)

**Comment by moisout** [comment]
Subscriptions have received a bunch of updates since version 0.10. Please open a new issue if problems occur.
