### ISSUE TITLE
"undefined is not an object (evaluating 'R.data.progressSeconds')" - using dev image

### ISSUE THREAD

**Issue by JesseWebDotCom** [mauriceoegerli/viewtube-vue#1964]
Using the dev image, you are able to play a video. But if you leave the video while playing (ex. go to the homepage) and go back to the same video, you will get the error:
"undefined is not an object (evaluating 'R.data.progressSeconds')"

This is only an issue when you have "Save video history and progress" enabled

**Comment by ghost** [comment]
I have the same issue using the `mauriceo/viewtube:latest` image.

**Comment by moisout** [comment]
I am currently working on a new video player #2387. It will fix this issue
