### ISSUE TITLE
[Feature request] Show thumbnails when the cursor points to the progress bar

### ISSUE THREAD

**Issue by ghost** [mauriceoegerli/viewtube-vue#2029]
### description

Show thumbnails when the cursor points to the progress bar.

### acceptance criterias

<img width="1280" alt="Screen Shot 2023-06-27 at 2 28 21 PM" src="https://github.com/ViewTube/viewtube/assets/33184148/5217d3c3-140c-470d-a414-037260257597">

**Comment by moisout** [comment]
I am currently working on a new video player #2387. It will have this feature.
