### ISSUE TITLE
demo website down

### ISSUE THREAD

**Issue by M1CK431** [mauriceoegerli/viewtube-vue#2041]
### Describe the Bug

![image](https://github.com/ViewTube/viewtube/assets/31622263/5480892a-0913-4e9b-b062-61630898a4d6)

### Steps to Reproduce the Bug

open https://dev.viewtube.io
OR
open https://viewtube.io

### Expected Behaviour

Try ViewTube, The open source, privacy-conscious way to enjoy my favorite YouTube content 😜 

### Screenshot/Screen recording

![image](https://github.com/ViewTube/viewtube/assets/31622263/6895e086-ad41-430d-8241-27f31a0a310e)

### Device Info

Not relevant

### Additional Context

I would be so happy to give it a try...

**Comment by moisout** [comment]
My server ran out of space 😅. I am working on it

**Comment by moisout** [comment]
They are up!

**Comment by M1CK431** [comment]
Can confirm it works! thanks 😘
