### ISSUE TITLE
Error loading playlist: Playlist may not be available

### ISSUE THREAD

**Issue by M1CK431** [mauriceoegerli/viewtube-vue#2050]
### Describe the Bug

![image](https://github.com/ViewTube/viewtube/assets/31622263/f1796502-1cad-488c-819c-cab7734d6317)

### Steps to Reproduce the Bug

Open: https://viewtube.io/watch?v=LssoZSwZXu0&list=RDnfBGWqfPdpo&index=34
This link is a "mix" playlist autogenerated by youtube based on my history.
On youtube website, they looks like this:
![image](https://github.com/ViewTube/viewtube/assets/31622263/09638c24-9aa7-4075-aa3f-f09d7507f3a6)

### Expected Behaviour

The perfect behavior would be the feature parity with youtube:
![image](https://github.com/ViewTube/viewtube/assets/31622263/09c7ad74-3879-44ee-8189-777695d55a50)

But at least:
- no error message
- playlist is loaded, displayed, played

### Additional Context

With youtube recent fight against ad blocker, a lot of people will look for alternative and that "mix" playlist autogenerated is a very used feature, especially for people who want to discover new music based on their preferences. If Viewtube gain support for that, it might be the way to glory! 🏆 

perhaps related to #74 🤷🏼‍♂️

**Comment by moisout** [comment]
I don't think it's possible to support this kind of playlist, since it is generated individually per account. If you open it in an incognito window, there will be no playlist.

**Comment by M1CK431** [comment]
Do you mean it will works if I login with my google account in ViewTube? 🤔

**Comment by M1CK431** [comment]
Mmm just realize: the sign in/up is not related to google account... So no way to make it works I guess 😢 
Thanks anyway for your so quick reply! 😘
