### ISSUE TITLE
Artefacts in forms not loading correctly 

### ISSUE THREAD

**Issue by pawisoon** [mauriceoegerli/viewtube-vue#2051]
Many artefacts like icons / headers won't load correctly. 

on: https://dev.viewtube.io

e.g. Login / signup form / icons below video 

`mdi:account-outline, mdi:key-outline`

<img width="1315" alt="Screenshot 2023-07-09 at 21 54 36" src="https://github.com/ViewTube/viewtube/assets/6951295/7736502a-1f25-4b39-b638-dfc39f6f1364">

**Comment by moisout** [comment]
Fixed on https://dev.viewtube.io!

**Comment by pawisoon** [comment]
What was the issue? Will it require an update to fix it on my instance?

**Comment by pawisoon** [comment]
> Fixed on https://dev.viewtube.io!

What was the issue? Will it require an update to fix it on my instance?

**Comment by moisout** [comment]
> > Fixed on https://dev.viewtube.io!
> 
> What was the issue? Will it require an update to fix it on my instance?

If you update to the latest version, it will be fixed. There was an issue with the icons not being included in the build.
