### ISSUE TITLE
Missing channels/videos

### ISSUE THREAD

**Issue by jimmisavage** [mauriceoegerli/viewtube-vue#2080]
### Describe the Bug

I can't find some channels when searching. A search for teddy baldassarre returns no videos, also a search for marques brownlee returns no videos on my install but does on the public one https://viewtube.io/. teddy baldassarre also returns no results on the public instance https://viewtube.io/

### Expected Behaviour

Channel and videos to show

### Device Info

- Device: synology NAS - docker
- Browser: chrome
-  used this website to install: https://mariushosting.com/how-to-install-viewtube-on-your-synology-nas/

### Additional Context

These aren;t the only channels/videos missing, these are just a couple of examples i have found after the first few minutes of testing.

**Comment by jimmisavage** [comment]
A little mor information - I can go directly to the channel by using www.myurl/channel/UCBJycsmduvYEL83R_U4JriQ (adding the channel link directly)

**Comment by moisout** [comment]
Youtube changed some things again, i am working on fixing this issue

**Comment by moisout** [comment]
Should be fixed in 0.11.0!
