### ISSUE TITLE
Can't search... Search comes up blank

### ISSUE THREAD

**Issue by XfEnE** [mauriceoegerli/viewtube-vue#2106]
### Describe the Bug

When doing a search no results come back

### Steps to Reproduce the Bug

1. type in something to search for and hit enter , nothing comes back.

### Expected Behavior

When typing in a search and pressing enter or clicking the magnifier icon there should come back with results

### Screenshot/Screen recording

{"statusCode":500,"message":"Error getting filters for games","error":"Internal Server Error"}

XHRGET
https://viewtube.io/api/search/filters?q=games
[HTTP/2 500 Internal Server Error 899ms]

	
GET
	https://viewtube.io/api/search/filters?q=games
Status
500
Internal Server Error
VersionHTTP/2
Transferred1.69 kB (94 B size)
Referrer Policyno-referrer
Request PriorityHighest

    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Host
    	viewtube.io
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

error FetchError: 500 Internal Server Error (/api/search/filters?q=games)
    NuxtJS 35

TypeError: t is null
    NuxtJS 48

### Device Info

- Device: PC 
- OS: Windows 10
- Browser: Firefox, Chrome, Brave
- Version: 1115.0.3, 115.0.5790.110,

**Comment by moisout** [comment]
It's a known issue, i am working on fixing it!😊

**Comment by moisout** [comment]
Fixed in version 0.11.0 :)
