### ISSUE TITLE
Blank start page, blank search page

### ISSUE THREAD

**Issue by kitefreakk** [mauriceoegerli/viewtube-vue#2135]
### Describe the Bug

No videos are shown anywhere.

### Steps to Reproduce the Bug

Running as Docker, Installed from Unraid Community Apps.

### Expected Behaviour

Videos show up on the front page and in search

Swagger UI is accessible on domain.com/api and looks identical to the one found on viewtube.io/api
logs show no errors, mongodb and redis are working or at least appear to be working. 
I am unclear on what to input as: VIEWTUBE_API_URL currently I have it set to https://viewtube.io/api/ but I have tried my own domain with https and http domain.com/api as well as the localhost ip.
VIEWTUBE_CORS_ORIGIN is set to the domain I wish to access it from.

**Comment by mikezila** [comment]
I think that Viewtube is broken currently due to changes on Youtube's end. There are other issues (#2106, #2080) where it's been indicated that updates are needed to work with the new changes.

**Comment by moisout** [comment]
I just released version 0.11.0! Not all is well yet, but most stuff should work again :)

**Comment by kitefreakk** [comment]
Sweet, it indeed works now. However I am unable to subscribe to channels 😅

**Comment by mikezila** [comment]
I'll mirror what @kitefreakk reports. Most functions are working great, the only wrinkle I've noticed is that subscriptions do not work. Thank you for your work on this!

**Comment by moisout** [comment]
I am working on this with a friend right now! I'll track progress here #2144
