### ISSUE TITLE
search function broken

### ISSUE THREAD

**Issue by TestNintendo** [mauriceoegerli/viewtube-vue#2145]
### Describe the Bug

Unable to search anything.

### Steps to Reproduce the Bug

1. Search for anything.

### Expected Behaviour

The search results should appear.

### Screenshot/Screen recording

[![no-results.png](https://i.postimg.cc/v87rQPWD/no-results.png)](https://postimg.cc/JtnDx5YW)

### Device Info

- Device: PC
- OS: Windows XP SP3
- Browser: Mypal
- Version: 29.3.0

### Additional Context

None at the moment.

**Comment by moisout** [comment]
Hi, it seems your browser is having issues displaying the page.
This project only runs on the latest browsers (Chrome latest, Firefox latest/ESR, Safari latest), and derivatives of those.
Your browser (mypal) seems to have a beta version based on firefox 68, maybe you can try that?

**Comment by TestNintendo** [comment]
i tried, didn't work sadly...
[![no-results-again.png](https://i.postimg.cc/65rScP4R/no-results-again.png)](https://postimg.cc/7fLmYmVY)

**Comment by moisout** [comment]
I tried it with mypal 68.13.1 and it worked for me. Would you be able to send a screenshot of your browser console?

**Comment by TestNintendo** [comment]
yup, here you go
[![console-log.png](https://i.postimg.cc/jd1KJP4w/console-log.png)](https://postimg.cc/9rys64SC)

**Comment by TestNintendo** [comment]
and i'm using mypal 68.12.2b btw

**Comment by moisout** [comment]
Unfortunately your browser doesn't support web features needed for viewtube. You'd need to use a newer OS/Browser.
