### ISSUE TITLE
Search is dominated by shorts

### ISSUE THREAD

**Issue by mikezila** [mauriceoegerli/viewtube-vue#2152]
Trying to search for anything in Viewtube is a frustrating experience because the search results page is absolutely _plastered_ in shorts. It's worse than the real Youtube because at least there the shorts are in one section that scrolls sideways and doesn't take long to scroll past. On Viewtube every single search I try shows at most 4 real videos, then a massive block of shorts, then maybe 4 more videos, then another massive block of shorts, sometimes two massive blocks back to back.

It would be great if I could just turn shorts off completely. Failing that relegating them to their own tab would be fine. I understand that Viewtube scrapes the pages that Youtube gives it, but I would rather have nothing than a search page totally full of shorts. If the only non-shorts videos Youtube handed you were the four at the top and the four in-between the gigantic shorts blocks, it's fine to just show eight videos.

**Comment by moisout** [comment]
Search results are organized in shelves, the shorts-shelf has its own identifier. That could be filtered out.
![image](https://github.com/ViewTube/viewtube/assets/15955392/fb24bb0a-8a69-470e-aebb-1080cd62f20f)

**Comment by moisout** [comment]
Shorts filtering in search results has been released in version [0.16.0](https://github.com/ViewTube/viewtube/releases/tag/v0.16.0).
