### ISSUE TITLE
Configuration option to disable signup

### ISSUE THREAD

**Issue by CountCypher** [mauriceoegerli/viewtube-vue#2163]
### description
It would be great to have a configuration option to disable signup. This could by handy, for example, if you selfhost an instance that only you and your family uses. Once the family accounts are created, signup is not needed anymore.

### acceptance criterias

- [ ] configuration option implemented
- [ ] configuration option usable in docker-compose.yml through respective environment variable, for example, VIEWTUBE_SIGNUP

**Comment by asroxy** [comment]
Hey, not saying this shouldn't be done, but I have a self-hosted instance running over a Zerotier network so only those people on the network can access the site. And if you run a Mikrotik router, you could connect it to the Zerotier network, then add a routing table so a TV or any other device on the network can see the site without running Zerotier. May be a good solution and secure one until this is implemented.

**Comment by moisout** [comment]
Disabling Registration and Login everywhere was added in update [0.15.0](https://github.com/ViewTube/viewtube/releases/tag/v0.15.0). Read more here: https://viewtube.wiki/configuration/admin.

The Admin can create accounts through the admin panel.
