### ISSUE TITLE
Audio language gets changed

### ISSUE THREAD

**Issue by swaggerino** [mauriceoegerli/viewtube-vue#2333]
### Describe the Bug

So I'm selfhosting on unraid and everything is working great apart from the fact that on some videos, instead of the original audio I'm hearing other languages. 
I assume it takes some random (autogenerated?) subtitle and reads it out loud.

### Expected Behaviour

Play video with original audio

### Device Info

- Device: Laptop
- OS: Win 11
- Browser: Firefox
- Version: 118.0.2

**Comment by moisout** [comment]
Updated videoplayer is coming soon, with the ability to select language tracks. And the original language by default :)
