### ISSUE TITLE
Volume Controls have odd behaviour

### ISSUE THREAD

**Issue by shivalwolf** [mauriceoegerli/viewtube-vue#2342]
### Describe the Bug

1. When using the up/down arrow to control the volume of playback if you go down to 0% the audio mutes fully but the up arrow does not increase the volume again from 0%

2. New Videos always start at 100% volume. A resumed video starts at the previous set volume

### Steps to Reproduce the Bug

1. play a video
2. press down until 0 volume
3. attempt to press up arrow to increase the volume again does not work

### Expected Behaviour

1. Video should unmute and increase involume when pressing the up arrow from 0% volume

2. Volume should either have a default setting or volume should be the same as previous video played.

### Device Info

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 118

### Additional Context

Docker Dev verion of viewtube:
Version: 0.13.0
Last commit: d069a24b5d085cfbe8e483fa2918c406e790ef3f

**Comment by moisout** [comment]
I am currently working on a new video player #2387. It will fix this issue
