### ISSUE TITLE
Docs gone (viewtube.wiki)

### ISSUE THREAD

**Issue by rsaffi** [mauriceoegerli/viewtube-vue#2369]
### Describe the Bug

I decided to check out the docs for self-hosting Viewtube, but when opening https://viewtube.wiki I was met with a custom HTTP 404 page instead of documentation content.

### Steps to Reproduce the Bug

1. Go to https://viewtube.wiki
2. Get 404 Not Found

### Expected Behaviour

Docs are available.

### Screenshot/Screen recording

![image](https://github.com/ViewTube/viewtube/assets/15200226/d8c815f2-5281-4e80-8d67-5dc2a68ef2cc)

### Device Info

Irrelevant

**Comment by moisout** [comment]
Huh weird, I'll check it out

**Comment by moisout** [comment]
A deployment seems to have gone wrong. It's fixed now :)
