### ISSUE TITLE
SponsorBlock request is blocked

### ISSUE THREAD

**Issue by eglia** [mauriceoegerli/viewtube-vue#2382]
### Describe the Bug

SponsorBlock is not working in Firefox 119, creating the following error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://sponsor.ajay.app/api/skipSegments/675f?categories=[%22sponsor%22,%20%22intro%22,%20%22outro%22,%20%22interaction%22,%20%22selfpromo%22,%20%22music_offtopic%22,%20%22preview%22]’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).`
[learn more](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

### Steps to Reproduce the Bug

1. Open Developer Console in Firefox
2. Load any Video

### Device Info

- Device: -
- OS: Windows 10
- Browser: Firefox
- Version: 119

**Comment by moisout** [comment]
I am currently working on a new video player #2387. It will fix this issue
