### ISSUE TITLE
Watched history

### ISSUE THREAD

**Issue by jasoncrevier** [mauriceoegerli/viewtube-vue#2400]
### description

Would be nice if a user could see a history of the videos they've watched.

### acceptance criterias

- [ ] Users can see their watched history

**Comment by moisout** [comment]
You can! Create an account and visit your profile page.
Click the profile icon and then click "Your profile".
https://viewtube.io/profile

**Comment by jasoncrevier** [comment]
Oops! Somehow I clicked around everywhere but managed to miss my profile. Sorry for the unnecessary ticket!
