### ISSUE TITLE
Account Deletion issue

### ISSUE THREAD

**Issue by Eliya-Manoj** [mauriceoegerli/viewtube-vue#2403]
### Describe the Bug

Deletion of account is not possible.

### Steps to Reproduce the Bug

1. Go to Account
2. Click on Your Profile
3. Click Delete account
4. Give username and click delete account
5. See the issue

Delete account go to profile# page ( Current page )

### Expected Behaviour

Delete account

### Device Info

- Device: [e.g. Samsung M31]
- OS: [e.g. Android 12]
- Browser: [e.g. Firefox]
- Version: [e.g. 119.1]

**Comment by moisout** [comment]
Will be released with 0.14.3
