### ISSUE TITLE
When filling in login fields, keyboard controls used for populating the Fields do control the Video in background too.

### ISSUE THREAD

**Issue by onethree7** [mauriceoegerli/viewtube-vue#2427]
### Describe the Bug

When filling in login fields, keyboard controls used for populating the Fields do control the Video in background.

### Steps to Reproduce the Bug

1.  Build fresh appliance
2.  Start a Video
3.  Click on "login" , get the small login-window
4.  While typing username, password and the captcha, all keystrokes are going to login field AND also the background video skipping back and forth and pausing , muting, etc etc. 

### Expected Behaviour

If user Prompt-windows are open, do hide the pass-through to the videoplayer which is in background

### Screenshot/Screen recording
-na

### Device Info

- Device: PC
- OS: Win10, selfbuild appliance on ubuntu, 
- Browser: Chrome
- Version: 119.0.6045.125 (Offizieller Build) (64-Bit)

**Comment by moisout** [comment]
I am currently working on a new video player #2387. I have added this to the list of planned features/fixes.
