### ISSUE TITLE
The videos in phones doesn’t work

### ISSUE THREAD

**Issue by Kiles71** [mauriceoegerli/viewtube-vue#2443]
### Device Info

- Device: [iPhone 11]
- OS: [iOS 16.1.1 (20B101]
- Browser: [ Safari]
- Version: []

**Comment by arjpar** [comment]
+1 i also have this issue

**Comment by Savanta** [comment]
+1

**Comment by alangrafu** [comment]
+1

**Comment by smashkins** [comment]
in a self-hosted container instance on DS923+ play videos on iOS Device is very slow. On mac is very fast!! Why ? + 1

**Comment by moisout** [comment]
iOS Safari playback for the videoplayer is on the roadmap: #2387. I am working on an implementation.
