### ISSUE TITLE
default (admin) user?

### ISSUE THREAD

**Issue by Klar** [mauriceoegerli/viewtube-vue#2446]
is there a pre generated admin account or default user?

how can I access admin information / settings?

is there a way to enable / disable registrations?

Thanks

**Comment by moisout** [comment]
Sorry i havent updated the wiki yet about this, will post a link here once i have

**Comment by moisout** [comment]
Admin page docs here: https://viewtube.wiki/configuration/admin
There aren't a lot of options currently, but i'm working on settings for registration and login
