### ISSUE TITLE
Force landscape fullscreen

### ISSUE THREAD

**Issue by 12nick12** [mauriceoegerli/viewtube-vue#2468]
I never had screen rotate enabled on my phone. It would be great to have the option for force fullscreen to go landscape.

**Comment by moisout** [comment]
Firefox mobile switches to landscape for me when going into fullscreen. I'll see if i can figure out a reliable way.

**Comment by moisout** [comment]
Unfortunately, there is no web API to change the screen orientation.
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation
The only thing a website can do is lock it, which I don't think is useful for ViewTube.
https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock
