### ISSUE TITLE
Share (Original YouTube link)

### ISSUE THREAD

**Issue by jame25** [mauriceoegerli/viewtube-vue#2487]
I run a local instance of ViewTube (with a lan ip as the address) and I'd like to use the 'Share' feature to provide the original YouTube url for others.

**Comment by AeliusSaionji** [comment]
I have the same use case, would love to see this.

If it's not too much trouble, could we also include the youtube url somewhere on each thumbnail in search/subs/etc views?

For easy url sharing from all views, and also so it's easier to pass urls to mpv via browser extension.

Thanks.

**Comment by ewoks** [comment]
great that there are movements on this :clap: will it land in next release?

**Comment by patgruber** [comment]
I think this issue can be closed, since as far as I can see the merged PR was part of release v0.15.2

**Comment by jame25** [comment]
I appreciate that this feature has now been implemented, however as I mention in OP - I run a local instance of ViewTube (without SSL). The 'Copy YouTube Link' button does not work in this scenerio. 
![viewtube](https://github.com/ViewTube/viewtube/assets/13631646/1afc0cc7-8f49-4145-ba78-00a3c1a7ebc2)
