### ISSUE TITLE
Video player is not displaying

### ISSUE THREAD

**Issue by themisir** [mauriceoegerli/viewtube-vue#2504]
The video player was invisible on `watch` page. I didn't saw any errors being logged so was curious to find out more. After a bit of digging I found out that the `height` attribute of the vide player component gets set to `NaN` value (`NaN * 100vw` to be exact).

To confirm my findings I modified the value using web inspector and indeed the video player was displaying and working correctly. However, my friend didn't had the same issue, or nor did I when i tried with alternative browsers (I am not including browser information intentionally to promote the idea of cross-browser compatibility).

I decided to dig into the source code to why would the value be set to `NaN`, and found out that somehow `e.target.videoHeight / e.target.videoWidth` returns NaN. I got curious and did some light research and apparently the callback method used for resolving aspect ratio (and other initialization code) is apparently not reliable. Some video formats, some browser versions and even sometimes just because of pure lack of luck the callback may get called while video size being set to zero.

I (am going to add) added a linked PR to solve the issue, I explained my solution in the PR description.

**Comment by moisout** [comment]
https://github.com/all-contributors please add @themisir for code
