### ISSUE TITLE
Window is not defined error when playing some videos

### ISSUE THREAD

**Issue by jasoncrevier** [mauriceoegerli/viewtube-vue#2511]
### Describe the Bug

Some videos won't play. Instead, the page says "Video Error" and displays an error message: "window is not defined"

### Steps to Reproduce the Bug

1. Go to <viewtube-instance>/watch?v=yc40gS2q7DI (example of video that doesn't play, but there are others -- appears to be random)
2. See the error

### Expected Behaviour

Video should play like normal.

### Screenshot/Screen recording

![image](https://github.com/ViewTube/viewtube/assets/106266438/9d9c5ae6-8dfa-40ee-a8d9-04a9436011b5)

### Device Info

- Device: VPS
- OS: Ubuntu 22.04.3 (running via docker)
- Browser: Firefox
- Version: 0.13.0

**Comment by jasoncrevier** [comment]
Update: Tried that URL again today and it works, so it looks like this is an intermittent issue. But still an issue I've seen come up a number of times.

**Comment by moisout** [comment]
Yeah i forgot to pay for the vpn sorry

**Comment by jasoncrevier** [comment]
Are you able to elaborate on what that means @moisout ?

**Comment by moisout** [comment]
@jasoncrevier ofcourse! The ViewTube server runs behind a vpn, because google blocks your ip address if you make too many requests. The VPN switches its IP address often enough so it doesn't get blocked.

**Comment by jasoncrevier** [comment]
@moisout got it, thank you! 🙂
