### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by misleadingrhino** [mauriceoegerli/viewtube-vue#2532]
### Describe the Bug

Changing anything in the settings is not saved on refresh.

### Steps to Reproduce the Bug

1. Click on profile name, then Settings.
2. Change anything.
3. Refresh page, changes have disappeared.

### Expected Behaviour

Changes saved.

### Device Info

- Device: Windows, Linux, Android
- OS: Windows 11, Ubuntu 18.04, Android 14
- Browser: Firefox
- Version: 14.2, 15

**Comment by moisout** [comment]
Hi, thank you for opening this issue. Are you logged in or not?

**Comment by misleadingrhino** [comment]
Yes, I'm logged in.

**Comment by moisout** [comment]
Theme setting wasn't being saved, i fixed that in release 0.15.1. Will be available soon on viewtube.io

**Comment by misleadingrhino** [comment]
The theme now saves, as do the rest of the settings, except for Default Video Speed. That one always goes back to 1.

Thank you for fixing the others!
