### ISSUE TITLE
Default video speed setting doesn't save

### ISSUE THREAD

**Issue by moisout** [mauriceoegerli/viewtube-vue#2538]
_Originally posted by @misleadingrhino in https://github.com/ViewTube/viewtube/issues/2532#issuecomment-1879916870_

**Comment by frozenduck** [comment]
Is it possible to reproduce this issue now ? I tried it, my default speed is saved correctly.

**Comment by gabriel-eladi** [comment]
i'm also having this issue on the latest version

**Comment by moisout** [comment]
Fixed as of release [0.16.0](https://github.com/ViewTube/viewtube/releases/tag/v0.16.0)
