### ISSUE TITLE
Wrong audio language/can't choose audio track

### ISSUE THREAD

**Issue by morsik** [mauriceoegerli/viewtube-vue#2563]
### Describe the Bug

Just heard about this project, tried on 2 random videos and... first bug already found :D

Wrong audio track.

### Steps to Reproduce the Bug

1. To go https://viewtube.io/watch?v=4dR5lbF5-wo
2. Audio is in Spanish (or whatever?)

### Expected Behaviour

Audio should be in English (or whatever I prefer).

Original video has multiple audio tracks, I couldn't find option to change audio track in ViewTube. Settings contain only "Video quality", "Audio quality" and "Other settings" about loop and speed.

### Device Info

- Device: MacBook Pro M2 Pro Max
- OS: macOS Sonoma 14.2.1
- Browser: Firefox 121.0

**Comment by moisout** [comment]
This is already in the works! Check out the issue for the new video player where you can track the progress! #2387
