### ISSUE TITLE
Cleaner Interface: Remove Trending Videos and Recommended Videos

### ISSUE THREAD

**Issue by StarOverSky** [mauriceoegerli/viewtube-vue#2587]
### description

It would be great to be able to remove Trending Videos from the Homepage and leave just a clean search interface or Subscriptions view.

Please add an option to remove/hide recommended videos.

**Comment by neuleo** [comment]
+1

**Comment by JohnnyPicnic** [comment]
Being able to remove the trending videos would be a huge improvement for me.

**Comment by moisout** [comment]
@nargacu83 Just added this via PR. It is on dev, will be available in next release!

**Comment by ewoks** [comment]
Thanks for improving this @moisout. 
Can we consider expanding subscription to the all available space when trending is turned off? 
Please share your opinion on this

**Comment by nargacu83** [comment]
> Thanks for improving this @moisout. Can we consider expanding subscription to the all available space when trending is turned off? Please share your opinion on this

I just added this and has been merged on dev.

**Comment by moisout** [comment]
Thanks a lot @nargacu83!

I will make a new release soon, with this included.

**Comment by ewoks** [comment]
Notes to the others who look for how to it:

I confirm it is possible now to remove trending videos via:
Profile -> Settings -> Homescreen (section) -> and than switch off the toggle for "Show trending videos on home screen"

as well as to turn of recommended videos via:
Profile -> Settings -> Enchancements  (section) -> and than switch off the toggle for "Show recommended videos on a video page"

Thanks everyone for great work and contributions!!! :rocket:
