### ISSUE TITLE
turn off auto quality...

### ISSUE THREAD

**Issue by CinnamonShaey** [mauriceoegerli/viewtube-vue#2608]
### description
im using the latest version of viewtube, hosting it myself, for some reason even with automatically adjust turned off it still adjusts depending on my screen size, which i do not want, im running a lesser known resolution of 2560:1080 but the app lowers the quality in videos cause of screen size, would be nice with a way to turn that off, so i could choose the resolution myself, ive even set the default resolution in the settings to 4k even tho i know i wont get anything out of it, but i would still like the choice to do so instead of the app just blocking me

also for some reason home pages of creators dont load for me? dont know what causes this tho

Describe your Feature Request
i would like a way to manually select quality without restrictions of screen size 

### acceptance criterias

- [ ] no sure what to write here, but yea i would like this feature

**Comment by moisout** [comment]
The new video player will have better quality selection, without limitations. You can check out this issue: https://github.com/ViewTube/viewtube/issues/2387

**Comment by CinnamonShaey** [comment]
> The new video player will have better quality selection, without limitations. You can check out this issue: #2387

i might be blind, but is there an ETA for this? or is it just in development?

**Comment by moisout** [comment]
> > The new video player will have better quality selection, without limitations. You can check out this issue: #2387
> 
> i might be blind, but is there an ETA for this? or is it just in development?

I am actively develping it currently, but I am just one guy doing this in his free time. So I really can't give an ETA, I hope you understand :)

**Comment by CinnamonShaey** [comment]
> > > The new video player will have better quality selection, without limitations. You can check out this issue: #2387
> > 
> > 
> > i might be blind, but is there an ETA for this? or is it just in development?
> 
> I am actively develping it currently, but I am just one guy doing this in his free time. So I really can't give an ETA, I hope you understand :)

oh for sure, what you have made is already impressive! like if the quality gets fixed and we get some kind of watch later feature, then i would be ready to switch permanently, so yea, take your time and make the best product you can, quality over quantity kind of thing :D
