### ISSUE TITLE
GET "/api/videos/[......]" :500

### ISSUE THREAD

**Issue by filobus97** [mauriceoegerli/viewtube-vue#2663]
As also mentioned in other issues, I get this error when trying to play any video on my self hosted istance, but I still am able to browse my subscriptions, with thumbnails and titles.
Anyway, only the subscription tab is working, while search and recommended videos are not shown.

On my host (a raspberry pi 5) I see the redis service is using an unusually high ram amount. I never noticed values this high when it was working.

Also some public istances of viewtube seemed completely unresponsive when I tried.

**Comment by moisout** [comment]
Fixed with release 0.15.2!
