### ISSUE TITLE
Unable to Input YouTube Shortcut Keys During Account Login or Registration While Video Plays in Background

### ISSUE THREAD

**Issue by yaseen-kc** [mauriceoegerli/viewtube-vue#2670]
### Describe the Bug

When attempting to type the lowercase letter "k" while watching a video and simultaneously trying to sign up or sign in by clicking on the corresponding button in the top right corner, the video pauses instead of inputting the letter "k".

### Steps to Reproduce the Bug

1. Play any video from the home screen.
2. Click on the sign-up or sign-in button located at the top right corner.
3. Attempt to type the lowercase letter "k".

### Expected Behaviour

Typing the lowercase letter "k" should input the character into any input fields, and the video should continue playing without interruption.

### Screenshot/Screen recording

https://github.com/ViewTube/viewtube/assets/60836135/5c646081-b8c8-4da4-87d8-0848a8f1fd8a

### Device Info

- Device: [ASUS VivoBook 15 X509FJ-EJ501T]
- OS: [Windows 11 23H2]
- Browser: [Brave Browser]
- Version: [1.63.162 Chromium: 122.0.6261.69]

### Additional Context

The issue seems to be interfering with the keyboard input when attempting to type the letter "k" while the sign-up or sign-in overlay is active during video playback from the home screen. This behavior was observed consistently and affects the user experience negatively.

**Comment by yaseen-kc** [comment]
Issue is being encountered while using all YouTube shortcut keys, such as "k," "f," "j," etc.

**Comment by moisout** [comment]
@yaseen-kc Fixed in release [0.16.0](https://github.com/ViewTube/viewtube/releases/tag/v0.16.0) with new video player
