### ISSUE TITLE
Error building a development branch

### ISSUE THREAD

**Issue by frozenduck** [mauriceoegerli/viewtube-vue#2734]
### Describe the Bug

I get an error when I try to build a project

### Steps to Reproduce the Bug

1. Tried to run the command in the console "pnpm run build"

The previous commands completed without any errors or warnings, the necessary tools of the right versions are installed.

### Expected Behaviour

Successful build

### Screenshot/Screen recording

[Screenshot](https://i.postimg.cc/DfcV2JbS/viewtube-err-on-build.jpg)

### Device Info

- Device: Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 124.0.1

**Comment by moisout** [comment]
Hi! Try running `pnpm run build:metadata` and then building again

**Comment by frozenduck** [comment]
> Hi! Try running `pnpm run build:metadata` and then building again

Thank you, I was able to successfully build and run the project


At startup, there was still an error because the config.json file was missing from the path \viewtube\server\data\


I did not have the \data\ directory, so I created it manually and the project started successfully.
