### ISSUE TITLE
Raspberry pi and mongodb

### ISSUE THREAD

**Issue by gwenvador** [mauriceoegerli/viewtube-vue#2737]
The mongoDB in docker-compose viewtube is not compatible with raspberry pi4 and older hardware. For people having this issue consider using this repository: https://github.com/isaric/mongodb-raspberrypi-docker and replace  

 viewtube-mongodb:
    restart: unless-stopped
    image: mongo:7

with

 viewtube-mongodb:
    restart: unless-stopped
    image: ghcr.io/isaric/mongodb-raspberrypi-docker:7.0.3

**Comment by moisout** [comment]
I will add it to the docs, thank you

**Comment by moisout** [comment]
Docs updated: https://viewtube.wiki/installation/docker#running-on-systems-without-avx-support-eg-synology-nas
