### ISSUE TITLE
Error 500 on a livestream

### ISSUE THREAD

**Issue by nargacu83** [mauriceoegerli/viewtube-vue#2740]
### Describe the Bug

An error 500 happens when attempting to show a livestream.

### Steps to Reproduce the Bug

1. Go to https://viewtube.io/
2. Try to load any livestream like this one: https://viewtube.io/watch?v=jfKfPfyJRdk (lofi hip hop radio).
3. You should get the error in the Viewtube UI.

### Expected Behaviour

Loads the page with the livestream and being able to play to livestream.

### Screenshot/Screen recording

![image](https://github.com/ViewTube/viewtube/assets/11914315/6534a80b-a36d-4acd-8b87-a62eff9afbe2)

### Device Info

- Device: PC
- OS: Arch Linux
- Browser: Firefox
- Version: 0.15.2

### Additional Context

If you reload the page you get the error without the Viewtube UI.
It also sometimes happens on a channel's page as well, but i'm not sure how it happens.

**Comment by moisout** [comment]
Fixed on dev version, will be released in next version
