### ISSUE TITLE
Error 500 on some videos and channels

### ISSUE THREAD

**Issue by nargacu83** [mauriceoegerli/viewtube-vue#2769]
### Describe the Bug

Some videos and channels doesn't load and returns an error 500. 

A weird case for the channels is that it can sometimes load when clicking on links from search or on the channel link from a video page.
For a video, it doesn't load at all. 

### Steps to Reproduce the Bug

For a video:
1. Go to [Yakuza 0 - Majima Trailer | PS4](https://viewtube.io/watch?v=T1G7WCTy_g8)
2. See the error

For a channel:
1. Go to [Deebeegeek channel](https://viewtube.io/channel/UC9Ed9JvjK_UDDpj8C_tMaqg)
  It might requires a few page reload.
2. See the error

### Expected Behaviour

Shows the video or channel page.

### Screenshot/Screen recording

For a video:
![image](https://github.com/ViewTube/viewtube/assets/11914315/91f55b2a-a180-42de-a762-8c1d52bca559)

For a channel:
![image](https://github.com/ViewTube/viewtube/assets/11914315/76ac5afa-69b8-4bf4-8d5b-a6ab4fd6b375)

### Device Info

- Device: PC
- OS: Arch Linux
- Browser: Firefox
- Version: 0.15.3

### Additional Context

Could this be related to #2740?

**Comment by ghost** [comment]
Looks like it happens specifically on age restricted videos

**Comment by moisout** [comment]
There are two issues here:
- Channels are unreliable at the moment, because YouTube changed some things
  - Fix is coming sometime soon
- Age restricted videos can sometimes not be played
  - I added a message if a video is age-restricted: #2847
