### ISSUE TITLE
Video stuck loading with unreliable internet connection

### ISSUE THREAD

**Issue by Cwpute** [mauriceoegerli/viewtube-vue#2787]
### Describe the Bug

I have an unreliable internet connection and sometimes the upload and download speeds drop down to zero without losing connection. The problem is that ViewTubed gets stuck loading the video and once the conection picks up again it is unable to load the video from where it was before. I have to manually reload the page for Viewtube to load the video as usual.

### Expected Behaviour

I'd like the player to detect when the internet speed is back from zero/to normal and start downloading again so my video plays.

### Device Info

- Device: Linux computer
- OS: Mint 21.3
- Browser: Firefox
- Version: 125.0.2
- Viewtube instance: viewtube.io

**Comment by moisout** [comment]
The new video player (Implemented in release [0.16.0](https://github.com/ViewTube/viewtube/releases/tag/v0.16.0)) is a lot more reliable, and retries loading many times before giving up. I hope you will have better results with it!
