### ISSUE TITLE
Does not play on iOS

### ISSUE THREAD

**Issue by kiwinh0** [mauriceoegerli/viewtube-vue#2789]
### Describe the Bug

A self-hosted instance, the videos played from the iPhone load but do not play, they freeze at the beginning of the video. If you move forward, it is also frozen but in the selected part of the video. 

### Steps to Reproduce the Bug

1. Select any video
2. Play
3. Advance the video

### Expected Behaviour

Be able to play the video normally. 

### Screenshot/Screen recording

![capture](https://github.com/ViewTube/viewtube/assets/151359530/ad749f29-4007-42f7-830c-d57f9e1530e3)
 

### Device Info

- Device: iPhone 13 and iPhone 14
- OS: 17.4.1
- Browser: Safari
- Version: 17.4

### Additional Context

It only happens on iOS devices at the moment, probably due to webkit

**Comment by moisout** [comment]
iOS safari playback is on the video player roadmap, check here: #2387
