### ISSUE TITLE
Search returns 0 results

### ISSUE THREAD

**Issue by stemy2** [mauriceoegerli/viewtube-vue#2793]
### Describe the Bug
When i perform a search, it returns zero results, event if there are actually some results when i search on youtube itself.

### Steps to Reproduce the Bug

1. Go to the main instance
2. Perform a search
3. See nothing except "0 results" on the page

### Expected Behaviour
At least one result.

### Device Info

- Device: Desktop PC
- OS: Kubuntu 23.10
- Browser: Librewolf 125.0.2-1

**Comment by moisout** [comment]
This is fixed in #2844, it's available on the dev image and will be released soon
