### ISSUE TITLE
Compile error '@/buildMetadata.json'

### ISSUE THREAD

**Issue by blade10101** [mauriceoegerli/viewtube-vue#2797]
### Steps to Reproduce the Bug

docker compose up -d
nothing was changed in the compose file

### Expected Behavior

A successful compile

### Screenshot/Screen recording

64.20 client build: components/About.vue(5,53): error TS2307: Cannot find module '@/buildMetadata.json' or its corresponding type declarations.
64.32 client build: Failed
64.33 /home/build/client:
64.33  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  client@ build: `cross-env NUXT_BUILD=true nuxi build`
64.33 Exit status 1
64.39  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:19
--------------------
  17 |     COPY . .
  18 |
  19 | >>> RUN pnpm run build
  20 |
  21 |     RUN rm -rf node_modules client/node_modules server/node_modules shared/node_modules "$(pnpm store path)"
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm run build" did not complete successfully: exit code: 1
ERROR: Service 'viewtube' failed to build : Build failed

### Device Info

Ubuntu 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Docker version 26.1.2, build 211e74b

**Comment by moisout** [comment]
This will be fixed soon, in the meantime try running "pnpm build:metadata" before.
