### ISSUE TITLE
Ability to change content country.

### ISSUE THREAD

**Issue by KraiiFox** [mauriceoegerli/viewtube-vue#2827]
### Description

Not sure if this is already a thing, but I can't find any env variable or settings for it.

An option to change the content country for the trending page, right now it is based on the IP of the hosting server.

### Requests

- Environment variable set the default country.
- User setting to change the country.

**Comment by moisout** [comment]
This is now implemented. Use the VIEWTUBE_LOCATION environment variable.
https://viewtube.wiki/configuration/environment#advanced-configuration
