### ISSUE TITLE
Docker container reporting unhealthy status

### ISSUE THREAD

**Issue by bucketsadmin** [mauriceoegerli/viewtube-vue#2841]
### Describe the Bug

With the newest release, the internal healthcheck for the viewtube docker container is showing a constant unhealthy status. The application itself runs fine and when publishing the ports to the host viewtube is fully accessibly and running properly. 

However, due to the unhealthy status of the container any attached labels do not get published to the docker service. This is impacting the ability for services such as Traefik to properly route traffic to the container.

Error being reported by the internal healthcheck:

```
http://localhost:8066/: Remote file does not exist -- broken link!!!
```

Whatever values are expected to be returned in the healthcheck are not being presented by the internal webserver.

### Steps to Reproduce the Bug

Deployment via docker compose using the container from docker hub mauriceo/viewtube:latest.

### Expected Behaviour

Healthcheck completes successfully

### Screenshot/Screen recording

wget from external host:
![image](https://github.com/ViewTube/viewtube/assets/15117743/dd118fc1-8fbd-4c18-bc9f-e5b42e1cd703)

internal healthcheck report (portainer)
![image](https://github.com/ViewTube/viewtube/assets/15117743/5a11c6dc-4cf7-41ef-b048-0c2bb36325bc)

### Device Info

- Device: Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
- Container release: [0.16.1](https://hub.docker.com/layers/mauriceo/viewtube/0.16.1/images/sha256-963cec25ee9666b2c6d5225544d6ba7e5862abd9bbf5c12b65231f99e4ff562c?context=explore)
- OS: Ubuntu 22.04.4 LTS
- Browser: any
- Version: any

### Additional Context

Deploying the compose file via portainer and via docker compose up -d results in the same behavior on different Linux releases.

**Comment by moisout** [comment]
I've fixed in release [0.16.2](https://github.com/ViewTube/viewtube/releases/tag/v0.16.2), will be available on docker soon
