### ISSUE TITLE
Videos Fail To Play On iOS 18

### ISSUE THREAD

**Issue by privacytime101** [mauriceoegerli/viewtube-vue#2854]
### Describe the Bug

Video streams fail to load on iOS 18 Developer Beta 1. I'm not sure if this is an iOS bug, or an early warning for an upcoming change in iOS that'll break Viewtube. I'm unable to check the console because I don't have a Mac.

The client error given by Viewtube is: 
`Video playback error
MEDIA_SOURCE_NOT_SUPPORTED: No MediaSource Object was found in the current browser.`

### Steps to Reproduce the Bug

1. Open any video page
2. Try to play the video

### Expected Behaviour

In the latest version of iOS 17, videos work as expected.

### Device Info

- Device: iPhone12
- OS: iOS18.0 (22A5282m)
- Browser: WebKit-based (Tested: Safari, Vivaldi)
- Version: 0.16.3

**Comment by moisout** [comment]
iOS playback is not supported yet. It's on the [video player roadmap](https://github.com/ViewTube/viewtube/issues/2387).
