### ISSUE TITLE
Video stuck at loading animation.

### ISSUE THREAD

**Issue by ac1mx** [mauriceoegerli/viewtube-vue#2928]
Videos have recently gotten stuck at the loading animation. This happens no matter where the video is accessed from. It happens on all devices, on any internet connection, and also on all public instances I have been able to find. It also occurs on every current build, from nightly to latest. 
![image](https://github.com/ViewTube/viewtube/assets/79227977/41d17df7-60a6-4cd9-ae61-e98ed73289b1)
No errors appear in the log.

**Comment by patgruber** [comment]
Opened a pull request to fix the underlying issue: https://github.com/ViewTube/viewtube/pull/2931

What you can do to fix this is to execute the following command in the dev console: `localStorage.volume = '1'` and reload the page

**Comment by patgruber** [comment]
I think this issue can be closed, as the PR is already merged.
