### ISSUE TITLE
Massive Error by playing any video on any iPhone Safari any browsers.

### ISSUE THREAD

**Issue by Berkopl** [mauriceoegerli/viewtube-vue#2943]
### Describe the Bug

Error by playing any video on any iPhone Safari browser.

### Steps to Reproduce the Bug

- Device: [iphone 12]
- OS: [ios 17.5.1]
- Browser: [e.g. Chrome, Safari, EDGE, any browser]
- latest version
### Additional Context
The same Website, video working fine on iPad OS. 17.5.*

**Comment by shiny-comic** [comment]
iOS is not supported according to [this commment](https://github.com/ViewTube/viewtube/issues/2789#issuecomment-2171014945)

**Comment by Berkopl** [comment]
> iOS is not supported according to [this commment](https://github.com/ViewTube/viewtube/issues/2789#issuecomment-2171014945)
It worked for me before.

**Comment by shiny-comic** [comment]
> > iOS is not supported according to [this commment](https://github.com/ViewTube/viewtube/issues/2789#issuecomment-2171014945)
> 
> It worked for me before.
> 
> 

Maybe I'm wrong, but as I remembered the working image for iOS devices was the nighly build generated somewhere between 15 and 16.

**Comment by Berkopl** [comment]
I just deinstalled this and install a INVIDIOUS
