### ISSUE TITLE
Sponsorblock not work.

### ISSUE THREAD

**Issue by chirag127** [mauriceoegerli/viewtube-vue#663]
**Describe the bug** : A clear and concise description of what the bug is Sponsor block not working on segments starting at 0:00 . as they always plays for some second before skipping to the end of the segment .

**To Reproduce** 

1. Go to 'https://viewtube.io/watch?v=rYQgy8QDEBI or https://viewtube.io/watch?v=V7HBrSMEidc'
2. Enable all segment categories 
3. Click on 'play button'

**Expected behavior** A clear and concise description of what I expected to happen is that segment should get skipped completely .

**Desktop :**

- OS: Windows 
- Browser chrome 
- Version 
![image](https://user-images.githubusercontent.com/76880977/121299966-c87b0880-c913-11eb-9bea-06290808804e.png)

**Comment by moisout** [comment]
Thank you for opening this issue! 
It seems like it doesn't immediately start checking for sponsorblock segments. I'll look into it!

**Comment by chirag127** [comment]
How much time does it takes for commits on GitHub to reflect on the website ?

**Comment by moisout** [comment]
Normally, as soon as something is on the development branch, it's available on https://dev.viewtube.io.
If it's stable, i'll then release it to the main website.

But i'm having some build issues at the moment, which i'm sorting out.

**Comment by chirag127** [comment]
Is it some kind of bug that I can't login with same user name and password on https://dev.viewtube.io/ as with the credentials which I used on the https://viewtube.io/ or this is something done intentionally ?

**Comment by moisout** [comment]
Yeah, they are using separate databases.

**Comment by chirag127** [comment]
But why........ ???😂

**Comment by moisout** [comment]
Well, the dev version is the unstable one. So maybe i'll fuck something up and it breaks. If both would be using the same database, it would break on both versions. I hope that makes sense haha.

**Comment by chirag127** [comment]
Gotcha , but I think it's already broken I have to sign-up again with another user name after sometime as I get failed login error randomly een if I'm pretty sure that my password is correct after sometime with no option of even forget password ( which I think because you don't ask for any mail id because of privacy ) .


Did someone else also reported something like this or I'm the only one ?

**Comment by moisout** [comment]
Youre the first one, but i am aware of issues with the login. This project is just not that stable yet, I'm afraid.

**Comment by moisout** [comment]
But thanks for reporting issues, it helps a lot! :D

**Comment by chirag127** [comment]
By the way , How many signed up users are there ?

**Comment by moisout** [comment]
On viewtube.io, there's 190 sign ups. I don't know how many of those are active.

**Comment by moisout** [comment]
Finally, it skips the sponsorblock segment now instantly, you can check on https://dev.viewtube.io/watch?v=V7HBrSMEidc

**Comment by moisout** [comment]
v0.7.0 is now released, i'm gonna close this
