### ISSUE TITLE
Videoplayer: Playback speed

### ISSUE THREAD

**Issue by mizzunet** [mauriceoegerli/viewtube-vue#676]
### description
It would be very nice to have this feature. Invidious instance's video player has this. You can be able to pick from there I guess. Also the ability to change default playback speed as well.

**Comment by moisout** [comment]
Hi, thank you for submitting an issue. Playback speed, along with loop, etc. are planned features, and are coming soon!

**Comment by mizzunet** [comment]
Awesome 🌟

**Comment by moisout** [comment]
Hi, i have implemented playback speed and loop, it's available on the dev instance https://dev.viewtube.io. Please report any bugs, thank you!

**Comment by mizzunet** [comment]
Works perfectly!
Thanks you very much ❤️

**Comment by moisout** [comment]
You're welcome :D
