### ISSUE TITLE
Not have all sponsor block categories 

### ISSUE THREAD

**Issue by chirag127** [mauriceoegerli/viewtube-vue#698]
**Describe the bug**  A clear and concise description of what the bug is Sponsor block category of Preview/recap is not present is the settings .

**To Reproduce**

1. Go to 'website'
2. Click on 'setting'
3. Scroll down to 'Block ads and annoyances'

**Expected behavior**
A clear and concise description of what you expected to happen is that it should have all the categories.

**Screenshots**

![image](https://user-images.githubusercontent.com/76880977/124259262-f38bfd00-db4b-11eb-8a46-a2d50371b6de.png)

**Additional context**

This Came a couple week ago. But didn't report at that time thinking it will be taken care of itself.

**Comment by moisout** [comment]
Ah, i didn't catch that there is a new category for previews. Thanks for noticing!

**Comment by moisout** [comment]
I have added the category "preview" on the beta instance https://dev.viewtube.io. It will be released soon.
