### ISSUE TITLE
App request

### ISSUE THREAD

**Issue by Subbarao6338** [mauriceoegerli/viewtube-vue#730]
Please create Android app for Viewtube.
With import playlists from youtube.
Download option.

**Comment by moisout** [comment]
Hi! Making a separate android app for ViewTube would be quite an effort that i don't have time for. 
However, it is installable as a progressive web app. If you have the website open on your mobile device, there should be a button in your browsers menu labeled "Install", "Add to home screen", or similar. 
Also, support for playlists is coming very soon in the next release. 
A download option is also a planned feature.

**Comment by iwannet** [comment]
@Subbarao6338 If you want an android app, you can try https://www.pwabuilder.com/.
