### ISSUE TITLE
Invidious's autoplay and play next video are missing

### ISSUE THREAD

**Issue by vhill1994983376** [mauriceoegerli/viewtube-vue#762]
### description
This is exactly what I have been looking for, but It doesn't have autoplay or auto play next video like invidious does. Please add these things. Not sure if that would be difficult to add, but if it were added than it would complete this for me. 

### acceptance criterias
- [ ] Autoplay
- [ ] Play next video automatically

**Comment by moisout** [comment]
Thanks for creating this issue. It's not difficult to add, and it's coming soon!

**Comment by moisout** [comment]
Hi, i have implemented it, and it's available on https://dev.viewtube.io. Please report any bugs!
