### ISSUE TITLE
Past VODs for YouTube livestreams do not play/load

### ISSUE THREAD

**Issue by ghost** [mauriceoegerli/viewtube-vue#799]
**Describe the bug**
When trying to play a VOD of a past livestream the loading animation never ends while the video thumbnail is displayed behind it on the player. This happens on all devices desktop and mobile iOS/iPad.

**To Reproduce**

1. Go to any past livestream such as https://viewtube.io/watch?v=qZCj3I8j9IU
2. See the player does not load

**Expected behavior**
The VOD video should load normally and begin playback.

**Desktop (please complete the following information):**

- OS: Windows 10 (Build: 19043.1110)
- Browser: Brave
- Version: 1.27.111

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS: iOS 14.7.1
- Browser: Safari

**Comment by moisout** [comment]
Thank you for creating this issue. I think it happens because viewtube still thinks it's an active livestream and keeps trying to play it. Ill look into it!

**Comment by moisout** [comment]
I added an additional check for live streams, which should fix the issue. It's available on https://dev.viewtube.io. Please report any bugs!

**Comment by ghost** [comment]
Sweet I will report if I find anything
