### ISSUE TITLE
Import OPML fails many subscriptions

### ISSUE THREAD

**Issue by mizzunet** [mauriceoegerli/viewtube-vue#851]
**Describe the bug**
The OPML exported from Invidious, importing it to ViewTube fails too many subscriptions and only adds couple of subscriptions. 
And importing it again would add couple of more subscriptions, still most are being failed to import.

**To Reproduce**

1. Export OPML backup from Invidious(here's mine https://oshi.at/voYDQE)
2. Sign up and login into ViewTube
3. Go to Subscriptions and import the file

**Expected behavior**
Import all the channel subscriptions

**Screenshots**
![Screenshot_20210827-120636_Brave](https://user-images.githubusercontent.com/10193999/131083136-57e7e1b6-2fcd-4c9a-9f75-63a6a161cb5d.png)

- OS: [e.g. iOS] Android
- Browser [e.g. chrome, safari] Brave
- Version [e.g. 22] 1.28 Chromium 92
- Device: [e.g. iPhone6] OnePlus 5

**Additional context**

In http://dev.viewtube.io, this importing worked fine.

**Comment by moisout** [comment]
Hi, thank you for reporting this!

I tested it myself, and got the same result on both dev.viewtube.io and viewtube.io:
![image](https://user-images.githubusercontent.com/15955392/131126737-a5e1806a-4f62-49ca-b9a4-bf6d6536ea71.png)

However, i will test more and see if i find something.

There will be a new release soon. I will leave this issue open and test it again after the new version is up.

**Comment by Explosion-Scratch** [comment]
Happening to me, this feature is quite prohibitive.

**Comment by Explosion-Scratch** [comment]
Failing **all** subscriptions for me no matter what client I use (dev.viewtube.io/viewtube.io) and no matter what format I attempt to import (OPML, CSV)
