### ISSUE TITLE
"Unable to load more results" 

### ISSUE THREAD

**Issue by mizzunet** [mauriceoegerli/viewtube-vue#886]
**Describe the bug**
For any searching videos results, only some, then tapping More says 
"Unable to load more results"

**To Reproduce**

1. Search any term, say "test"
2. Scroll down to below
3. Tap on More
4. See the error 

**Expected behavior**
Display more videos 

**Screenshots**
![Screenshot_20210910-115658_Brave](https://user-images.githubusercontent.com/10193999/132809623-5e7a1b0c-0481-44eb-b467-1c5636965881.png)

**Smartphone (please complete the following information):**

- Device: OnePlus 5
- Browser: Brave 
- Version: 1.29

**Additional context**
Tried both https://dev.viewtube.com and https://viewtube.com

**Comment by moisout** [comment]
Thank you for reporting! I'll check it out

**Comment by moisout** [comment]
Fixed in #928
