### ISSUE TITLE
Special characters in search don't work

### ISSUE THREAD

**Issue by a-camacho** [mauriceoegerli/viewtube-vue#924]
### Describe the Bug

When searching for words with french special characters, a strange symbol appears.

### Steps to Reproduce the Bug
1. Go to search
2. Fill with "le règlement"
4. See the error

### Screenshot/Screen recording

![1](https://user-images.githubusercontent.com/29976133/134665473-5bfde64f-9df7-49c9-b73f-026777cf869c.png)

### Device Info 

- Device: Macbook
- OS: High Sierra
- Browser: Firefox 
- Version: 92

**Comment by moisout** [comment]
Thanks for reporting this! I'll look into it.

**Comment by moisout** [comment]
fixed in #929, should be available on dev.viewtube.io soon, and on viewtube.io after the next release
