### ISSUE TITLE
Some videos exist in 1080p but show only in 360p

### ISSUE THREAD

**Issue by a-camacho** [mauriceoegerli/viewtube-vue#925]
### Describe the Bug
Some videos ([example tested](https://www.youtube.com/watch?v=JXYNYzaGIns)) existing in high quality on Youtube can only be reproduced in viewtube in 360p.
Is that an expected behaviour and is there any reason I can't stream this video in 1080p in viewtube ?

### Screenshot/Screen recording
![2](https://user-images.githubusercontent.com/29976133/134665583-ee45a93f-bac4-45d6-9314-469bf33382a8.png)

### Device Info 

- Device: Macbook
- OS: High Sierra
- Browser: Firefox
- Version: 92

**Comment by moisout** [comment]
Hi, high quality playback is a relatively new feature, and only available on https://dev.viewtube.io, because there are still some bugs.
It will be released soon though, and will then be available on the normal instance viewtube.io.

**Comment by moisout** [comment]
High-quality playback is available now
