### ISSUE TITLE
YouTube Subscription Export / Import Format Incompatibility

### ISSUE THREAD

**Issue by intp56** [mauriceoegerli/viewtube-vue#927]
### Describe the Bug

YouTube Subscriptions export format is now changed (The process now must be done via https://takeout.google.com/), rendering the previous process / instructions (found at: https://viewtube.io/subscriptions) inoperable.

### Steps to Reproduce the Bug

1. Click Subscriptions (Upper Right)
2. Click "Import Subscriptions" (Underneath)
3. URL cited under Step 1 no longer offers export, and although this can still be done, the file name is changed and the format is now CSV. There is no way to submit the new subscriptions list.

### Expected Behaviour

To be able to export existing YouTube Subscriptions and import into ViewTube via its subscription import tool.

### Device Info 

- Browser: [e.g. Firefox, Safari]
- Version: [e.g. 22]

Device: IdeaPad 300-17ISK
OS: ElementaryOS Hera
Browser: Brave
Version: Current

**Comment by moisout** [comment]
Thanks for reporting this! I'll add it to the backlog

**Comment by intp56** [comment]
Great--Thanks much!
