### ISSUE TITLE
Manual Channel Subscriptions Not Available

### ISSUE THREAD

**Issue by intp56** [mauriceoegerli/viewtube-vue#930]
### Describe the Bug

Unfortunately the Subscribe button seems to be only very sporadically available. Is this a known issue?

### Steps to Reproduce the Bug

1. Go to any channel or video
2. Click "Subscribe"
3. Unfortunately the button is not clickable, most of the time.

### Expected Behaviour

To subscribe to a channel

### Device Info 

- Browser: [e.g. Firefox, Safari]
- Version: [e.g. 22]

Device: IdeaPad 300-17ISK
OS: ElementaryOS Hera
Browser: Brave
Version: Current

**Comment by moisout** [comment]
Hi, you can only subscribe to a channel when you're logged in. Are you sure this is the case?

**Comment by intp56** [comment]
Yes, quite sure, thanks. Just tested again, same result.

**Comment by moisout** [comment]
I see, i'll look into it

**Comment by acupofjose** [comment]
In the meantime, you can export to OPML using a userscript (like this one: https://greasyfork.org/en/scripts/418574-export-youtube-subscriptions-to-rss-opml)

**Comment by moisout** [comment]
I have created a fix in #941, but i will have to test it first. I will update this issue once it's deployed on dev.viewtube.io.

**Comment by moisout** [comment]
It's now on dev.viewtube.io, it's working for me. Can someone test it aswell?

**Comment by intp56** [comment]
> It's now on dev.viewtube.io, it's working for me. Can someone test it aswell?

Thank you--I attempted to sign in, but my normal credentials which work on the public site were unfortunately rejected.

**Comment by moisout** [comment]
Yes, the dev and normal site are using different databases, because dev is on the latest unstable version, while the normal site runs the latest release.
