### ISSUE TITLE
cant make it work for pi4

### ISSUE THREAD

**Issue by lukino188** [mauriceoegerli/viewtube-vue#974]
Hi, im trying to get it to work for pi4 on docker? is it possible to have it in the future the compatibility or a im doing anything wrong?

Thanks!

**Comment by moisout** [comment]
Hi, once i have fixed the ip issues, i will look into creating arm64 builds!

**Comment by lukino188** [comment]
> Hi, once i have fixed the ip issues, i will look into creating arm64 builds!

Great, thanks a lot! Love your project!
